# Debian JessiE with Java 7 installed.
# Build image with:  docker build -t clelson/gog:v1 .
FROM debian:jessie
#MAINTAINER Clelson Salles Rodrigues, https://github.com/clelson

# Instalação do java7
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java7-installer && \
    apt-get clean


# Instalação do Maven
ENV MAVEN_VERSION 3.3.9

RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

VOLUME /root/.m2

#CMD ["mvn"]

# Instalação do git commands
RUN apt-get install git


# Instalação do Jboss7
# use o comando a seguir para executar o jboss na porta 8080, com o portal AS na 9090, e com a senha de administração configurada 
# docker run -d -p 8080:8080 -p 9990:9990 -e JBOSS_PASS="mypass" nomeImage 
RUN apt-get install -y pwgen && \
    wget -q http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.tar.gz && \
    tar zxf jboss-as-7.1.1.Final.tar.gz && \
    rm jboss-as-7.1.1.Final.tar.gz && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i -r 's/jboss.bind.address.management:127.0.0.1/jboss.bind.address.management:0.0.0.0/' /jboss-as-7.1.1.Final/standalone/configuration/standalone.xml

ADD run.sh /run.sh
ADD set_jboss_admin_pass.sh /set_jboss_admin_pass.sh
RUN chmod +x /*.sh

# Exposed ENV
ENV JBOSS_PASS **Random**

EXPOSE 8080 9990
CMD ["/run.sh"]


    


